<p><?php echo $this->getMethod()->getTitle(); ?></p>

<?php
if($this->getInfo()->getOrder() && $this->getInfo()->getOrder()->getState() != 'canceled'){
	if($this->getInfo()->hasAdditionalInformation('boleto_url') && $this->getInfo()->hasAdditionalInformation('payment_id')){
		echo '<p>Compra via Z4money Gateway</p>';
		echo '<p><strong>ID do Pagamento:</strong> <span>' . $this->getInfo()->getAdditionalInformation('payment_id') . '</span></p>';
        echo '<button type="button" class="scalable go" onclick="window.open(\''. $this->getInfo()->getAdditionalInformation('boleto_url') .'\', \'_blank\')">Imprimir boleto</button>';
    }else{
        $url = Mage::helper('adminhtml')->getUrl('z4money_gateway/boleto/generate', ['order_id' => $this->getInfo()->getOrder()->getIncrementId()]);
        echo '<p style="float: left; width: 100%; padding: 10px; color: #FFF; background: #C00; box-sizing: border-box;">Boleto não gerado! <a href="'. $url .'" style="color: #FFF; text-decoration: underline;">Gerar boleto</a></p>';
    }
    echo '<br><br>';
}
?>
